server:
  port: 8080

spring:
    datasource:
        url: jdbc:mysql://root:SkqcbWFNsdcbqycYsocbwjLXRVlXqVxC@mysql.railway.internal:3306/railway
        username: root
        password: SkqcbWFNsdcbqycYsocbwjLXRVlXqVxC
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
         ddl-auto: none
        show-sql: false

jwt:
  private-key: J924vq5V69C+geVA+TTOnBkldd9qBQNHQRgOuCPEmRg=
